# Generated by Django 5.2 on 2025-09-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0003_alter_storehour_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storehour',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='storelocator.store'),
        ),
    ]
