# Generated by Django 5.2 on 2025-09-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0004_alter_storehour_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='hour',
            field=models.ManyToManyField(blank=True, related_name='stores', to='storelocator.storehour'),
        ),
    ]
