# Generated by Django 5.2 on 2025-09-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0005_store_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='hour',
        ),
    ]
