# Generated by Django 5.2 on 2025-09-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0006_remove_store_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.AddField(
            model_name='store',
            name='hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StoreHour',
        ),
    ]
