# Generated by Django 5.2 on 2025-09-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0007_remove_store_image_store_hours_delete_storehour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='hours',
            new_name='closing_hours',
        ),
        migrations.AddField(
            model_name='store',
            name='opening_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
