# Generated by Django 5.2 on 2025-09-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0008_rename_hours_store_closing_hours_store_opening_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='closing_hours',
            new_name='closing_hour',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='opening_hours',
            new_name='opening_hour',
        ),
    ]
