# Generated by Django 5.2 on 2025-09-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0009_rename_closing_hours_store_closing_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
        migrations.AddField(
            model_name='store',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
