# Generated by Django 5.2 on 2025-09-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0013_alter_store_main_image_alter_store_primary_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='store',
            name='primary_image',
        ),
        migrations.RemoveField(
            model_name='store',
            name='secondary_image',
        ),
    ]
