# Generated by Django 5.2 on 2025-09-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0015_store_main_image_store_primary_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='main_image',
            field=models.ImageField(blank=True, default='defaults/store_default.jpg', null=True, upload_to='store_images/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='primary_image',
            field=models.ImageField(blank=True, default='defaults/store_default.jpg', null=True, upload_to='store_images/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='secondary_image',
            field=models.ImageField(blank=True, default='defaults/store_default.jpg', null=True, upload_to='store_images/'),
        ),
    ]
