# Generated by Django 5.2 on 2025-09-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0016_alter_store_main_image_alter_store_primary_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
