# Generated by Django 5.2 on 2025-09-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0018_store_created_at_store_slug_store_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
