# Generated by Django 5.2 on 2025-10-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0020_city_slug_state_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
