# Generated by Django 5.2 on 2025-12-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0021_alter_state_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name_plural': 'stores'},
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['city'], name='storelocato_city_id_f1e4e2_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['latitude', 'longitude'], name='storelocato_latitud_5fbca9_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['slug'], name='storelocato_slug_9b69e3_idx'),
        ),
    ]
