# Generated by Django 5.2 on 2025-12-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0022_alter_city_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
