# Generated by Django 5.2 on 2025-12-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0023_alter_store_latitude_alter_store_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
    ]
