# Generated by Django 5.2 on 2025-12-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storelocator', '0024_alter_store_latitude_alter_store_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
