services:
  - type: web
    name: smokeshop
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        libyaml-dev \
        libcairo2-dev \
        libgirepository1.0-dev \
        libgdal-dev \
        pkg-config
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "gunicorn smokeshop.wsgi:application"
    envVars:
      - key: SECRET_KEY
      - key: GOOGLE_MAPS_API_KEY
      - key: DB_NAME
      - key: DB_USER
      - key: DB_PASSWORD
      - key: DB_HOST
      - key: DB_PORT